### PR TITLE
Added support for rotate info in exif

### PR DESCRIPTION
**Pull request by hasherdk**
I added support for rotation data saved in a photo's exif information. It could probably be made prettier, but it's working for me for now.

I also think I fixed a potential leak with $tmpPath, but my PHP knowledge is several year outdated, so I'm not 100 % sure what's right or wrong.

### CODE REVIEW

**Comment by cowai** [comment]
@hasherdk Great! Thanks. Can you set the indentation to 4 spaces?  ( I see that I actually have a method with 2 spaces as well), but most of the project is 4 spaces.
The code looks good. I don't see any issues.

**Comment by hasherdk** [comment]
Sure, I'll check the indentation.

**Comment by hasherdk** [comment]
@cowai Looks to me like it is 4 spaces already. Iirc, it was a bit messy before with both spaces and tabs, so I cleaned it up. :-)

**Comment by cowai** [comment]
@hasherdk lol, you're right. I was checking on my phone and somehow to me that looked like 2 spaces.

**Pull request merged**
